Repository ApiBR/vagas-aggregator-ui, pull requests merged in 2023-08, with the labels that each got.

#91 Display badge with API version and date
  .vscode/settings.json
  README.md
  src/Components/Layout/NavBar.js
  src/Helpers/FormatDate.js
  src/Hooks/useMetadata.js
  src/index.js
Labels: enhancement, javascript, size/M

#93 Add comments badge on issues
  src/Components/Issues/IssueItem.js
Labels: size/S

#95 Detect keyword in issue title
  package-lock.json
  package.json
  src/Components/Issues/IssueItem.js
Labels: size/S

#96 Update IssueItem.js
  src/Components/Issues/IssueItem.js
Labels: size/XS

#97 Update IssueItem.js
  src/Components/Issues/IssueItem.js
Labels: size/XS

#99 Update NavBar.js
  src/Components/Layout/NavBar.js
Labels: enhancement, javascript, size/XS

#102 Update IssueItem.js
  src/Components/Issues/IssueItem.js
Labels: size/XS

#103 Update IssueItem.js
  src/Components/Issues/IssueItem.js
Labels: size/XS

#107 Update IssueItem.js
  src/Components/Issues/IssueItem.js
Labels: enhancement, javascript, size/XS

#114 Update sonarcloud.yml
  .github/workflows/sonarcloud.yml
Labels: size/S

#115 Update size-label.yml
  .github/workflows/size-label.yml
Labels: size/S

#113 vagas_aggregator_ui_v1
  src/Components/Issues/IssueItem.js
Labels: size/M

#117 Timestamp Component Overflows Card in IssueItem in recrutadores
  src/Components/Authors/AuthorItem.js
  src/Components/Repositories/RepositoriesListGroup.js
Labels: bug, enhancement, size/S
